[package]
name = "sdkwork-routes-portal-app-api"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sdkwork_platform_portal_service.workspace = true
sdkwork_portal_service_host.workspace = true
sdkwork_routes_portal_common.workspace = true
sdkwork-web-core.workspace = true
uuid = { workspace = true }
