//! Generated API assembly bootstrap for sdkwork-portal.
//! Regenerated by pnpm api:assembly:materialize.
//!
//! Multi-surface merges mount shared infrastructure routes once at the assembly layer
//! so `/healthz`, `/livez`, `/readyz`, and `/metrics` are not duplicated per surface.

use axum::Router;
use std::sync::Arc;
use sdkwork_database_sqlx::DatabasePool;
use sdkwork_web_bootstrap::{ApiAssemblyContribution, PgPoolReadinessCheck, ReadinessCheck};
use sdkwork_web_core::{DomainContextInjector, HttpRouteManifest};
use sdkwork_portal_service_host::PortalServiceHost;

pub type ApiAssembly = ApiAssemblyContribution;

/// Assemble the portal application router against a caller-provided database
/// pool so the platform cloud gateway can share its process-wide PostgreSQL
/// pool (single shared-pool process contract).
pub async fn assemble_api_router_with_pool(pool: DatabasePool) -> Result<ApiAssembly, String> {
    let host = Arc::new(
        PortalServiceHost::from_pool(pool)
            .await
            .map_err(|error| format!("Portal service host bootstrap failed: {error}"))?,
    );
    let readiness_pool = host
        .database_pool()
        .as_postgres()
        .ok_or_else(|| "Portal requires a PostgreSQL database profile".to_owned())?
        .clone();
    assemble_api_router(ApiAssemblyContext {
        host,
        domain_context_injectors: Vec::new(),
        readiness_check: Arc::new(PgPoolReadinessCheck::new(readiness_pool)),
    })
    .await
}

pub struct ApiAssemblyContext {
    pub host: Arc<PortalServiceHost>,
    pub domain_context_injectors: Vec<Arc<dyn DomainContextInjector>>,
    pub readiness_check: Arc<dyn ReadinessCheck>,
}

pub async fn assemble_api_router(context: ApiAssemblyContext) -> Result<ApiAssembly, String> {
    let ApiAssemblyContext { host, domain_context_injectors, readiness_check } = context;
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_portal_app_api::gateway_mount(host.clone()).await);
    router = router.merge(sdkwork_routes_portal_backend_api::gateway_mount(host.clone()).await);
    let mut routes = Vec::new();
    routes.extend_from_slice(sdkwork_routes_portal_app_api::gateway_route_manifest().routes());
    routes.extend_from_slice(sdkwork_routes_portal_backend_api::gateway_route_manifest().routes());
    ApiAssemblyContribution::from_manifest(
        "sdkwork-portal",
        "SDKWork portal API",
        router,
        HttpRouteManifest::from_owned_routes(routes),
        domain_context_injectors,
        readiness_check,
    )
}

pub async fn assemble_app_api_contribution(context: ApiAssemblyContext) -> Result<ApiAssembly, String> {
    let ApiAssemblyContext { host, domain_context_injectors, readiness_check } = context;
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_portal_app_api::gateway_mount(host.clone()).await);
    let mut routes = Vec::new();
    routes.extend_from_slice(sdkwork_routes_portal_app_api::gateway_route_manifest().routes());
    ApiAssemblyContribution::from_manifest(
        "sdkwork-portal",
        "SDKWork portal App API",
        router,
        HttpRouteManifest::from_owned_routes(routes),
        domain_context_injectors,
        readiness_check,
    )
}

pub async fn assemble_backend_api_contribution(context: ApiAssemblyContext) -> Result<ApiAssembly, String> {
    let ApiAssemblyContext { host, domain_context_injectors, readiness_check } = context;
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_portal_backend_api::gateway_mount(host.clone()).await);
    let mut routes = Vec::new();
    routes.extend_from_slice(sdkwork_routes_portal_backend_api::gateway_route_manifest().routes());
    ApiAssemblyContribution::from_manifest(
        "sdkwork-portal",
        "SDKWork portal Backend API",
        router,
        HttpRouteManifest::from_owned_routes(routes),
        domain_context_injectors,
        readiness_check,
    )
}

