[package]
name = "sdkwork-api-portal-assembly"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Generated API assembly for sdkwork-portal application HTTP plane."

[lib]
name = "sdkwork_api_portal_assembly"
path = "src/lib.rs"

[dependencies]
sdkwork-database-sqlx.workspace = true
axum.workspace = true
tokio.workspace = true
sdkwork-web-bootstrap.workspace = true
sdkwork-web-core.workspace = true
sdkwork_portal_service_host = { package = "sdkwork-portal-service-host", path = "../sdkwork-portal-service-host" }
sdkwork-routes-portal-app-api = { path = "../sdkwork-routes-portal-app-api" }
sdkwork-routes-portal-backend-api = { path = "../sdkwork-routes-portal-backend-api" }
